// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_kraken_signature`, `get_nonce`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<KrakenRestClient>>
abstract class KrakenRestClient implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<KrakenRestClient> newInstance({
    required String apiKey,
    required String apiSecret,
  }) => RustLib.instance.api.crateApiRestClientKrakenRestClientNew(
    apiKey: apiKey,
    apiSecret: apiSecret,
  );

  /// Generic private request
  Future<Value> privateRequest({
    required String endpoint,
    required List<(Str, String)> payload,
  });

  /// Generic public request
  Future<Value> publicRequest({
    required String endpoint,
    required List<(Str, Str)> params,
  });
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Value>>
abstract class Value implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<str>>
abstract class Str implements RustOpaqueInterface {}
